public_key_ssh_location = "/Users/macintosh/.ssh/accor.pub"
private_key_location =  "/Users/macintosh/.ssh/accor"
my_ip = "46.193.67.71/32"
env_prefix = "dev"
image_name = "amzn2-ami-kernel-*-x86_64-gp2"
instance_type = "t2.micro"
